### PR TITLE
Disk Monitoring and Maintenance

### PR DESCRIPTION
**Pull request by nzoschke**
Monitor and log disk usage. Goes with https://github.com/convox/rack/pull/162/files
- Introduce a MonitorDisk 5 minute timer to measure and log disk utilization per instance id
- Introduce a RemoveDockerArtifacts utility to remove containers and images if disk > 80%
- Introduce a MonitorDmesg 5 minute timer to grep dmesg for indication of a read-only filesystem

This requires a kernel change to:
- Pick this up when it's released as convox/agent:0.4
- Write the Kinesis stream name to the disk on every instance
- Allow Kinesis PutRecord in addition to PutRecords
- Allow AutoScaling SetInstanceHealth

This also lays some breadcrumbs for sending disk measurements to CloudWatch.

### CODE REVIEW

**Comment by nzoschke** [comment]
Need to fix the IAM instance policy:

```
$ docker logs 52e3b9f2b66a
monitor new region=us-west-2 cluster=convox-Cluster-1NCWX9EC0JOV4
disk monitor hostname=52e3b9f2b66a
2015/11/12 01:19:13 error: AccessDenied: User: arn:aws:sts::901416387788:assumed-role/convox-IamRole-2B1GK98KX6BX/i-633a9bba is not authorized to perform: cloudformation:ListStackResources on resource: arn:aws:cloudformation:us-west-2:901416387788:stack/convox/*
	status code: 403, request id: [6270e7f6-88db-11e5-b0e5-85320ebd84d9]
```

**Comment by nzoschke** [comment]
Probably don't need to do a policy where writing an `/etc/convox/kinesis` file will do

**Comment by csquared** [comment]
:+1:

**Comment by mattmanning** [comment]
:+1:

**Pull request merged**
