### PR TITLE
Enhance logs

### PR DESCRIPTION
**Pull request by nzoschke**
Log instance ID, container ID, release ID and additional docker events to the app log stream.

```
^CChappie:agent noah$ convox logs --app httpd
2015-11-21 02:14:46 i-a2eb6f7b convox/agent:0.5 : Starting process ba178922a3fb
2015-11-21 02:14:46 i-a2eb6f7b httpd/web:RDAHGDQMGXP : AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
2015-11-21 02:14:46 i-a2eb6f7b httpd/web:RDAHGDQMGXP : AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
2015-11-21 02:14:46 i-a2eb6f7b httpd/web:RDAHGDQMGXP : [Sat Nov 21 02:14:46.575330 2015] [mpm_event:notice] [pid 1:tid 140159494530944] AH00489: Apache/2.4.17 (Unix) configured -- resuming normal operations
2015-11-21 02:14:46 i-a2eb6f7b httpd/web:RDAHGDQMGXP : [Sat Nov 21 02:14:46.575450 2015] [core:notice] [pid 1:tid 140159494530944] AH00094: Command line: 'httpd -D FOREGROUND'
2015-11-21 02:15:28 i-a3f60679 httpd/web:RIDVTRGGJEB : AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
2015-11-21 02:15:28 i-a3f60679 httpd/web:RIDVTRGGJEB : AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
2015-11-21 02:15:28 i-a3f60679 httpd/web:RIDVTRGGJEB : [Sat Nov 21 02:12:08.842821 2015] [mpm_event:notice] [pid 1:tid 139888180590464] AH00489: Apache/2.4.17 (Unix) configured -- resuming normal operations
2015-11-21 02:15:28 i-a3f60679 httpd/web:RIDVTRGGJEB : [Sat Nov 21 02:12:08.842945 2015] [core:notice] [pid 1:tid 139888180590464] AH00094: Command line: 'httpd -D FOREGROUND'
2015-11-21 02:15:28 i-a3f60679 httpd/web:RIDVTRGGJEB : [Sat Nov 21 02:15:28.546170 2015] [mpm_event:notice] [pid 1:tid 139888180590464] AH00491: caught SIGTERM, shutting down
2015-11-21 02:15:28 i-a3f60679 convox/agent:0.5 : Stopped process ebc7bf234805
2015-11-21 02:15:28 i-a3f60679 convox/agent:0.5 : Stopping process ebc7bf234805 via SIGTERM

2015-11-21 02:20:29 i-a3f60679 convox/agent:0.5 : Starting process 9eabcf7d9953
2015-11-21 02:20:29 i-a3f60679 httpd/web:RIDVTRGGJEB : AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
2015-11-21 02:20:29 i-a3f60679 httpd/web:RIDVTRGGJEB : AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
2015-11-21 02:20:29 i-a3f60679 httpd/web:RIDVTRGGJEB : [Sat Nov 21 02:20:29.257000 2015] [mpm_event:notice] [pid 1:tid 140492121446272] AH00489: Apache/2.4.17 (Unix) configured -- resuming normal operations
2015-11-21 02:20:29 i-a3f60679 httpd/web:RIDVTRGGJEB : [Sat Nov 21 02:20:29.257125 2015] [core:notice] [pid 1:tid 140492121446272] AH00094: Command line: 'httpd -D FOREGROUND'

2015-11-21 02:21:07 i-a2eb6f7b httpd/web:RDAHGDQMGXP : AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
2015-11-21 02:21:07 i-a2eb6f7b httpd/web:RDAHGDQMGXP : AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
2015-11-21 02:21:07 i-a2eb6f7b httpd/web:RDAHGDQMGXP : [Sat Nov 21 02:14:46.575330 2015] [mpm_event:notice] [pid 1:tid 140159494530944] AH00489: Apache/2.4.17 (Unix) configured -- resuming normal operations
2015-11-21 02:21:07 i-a2eb6f7b httpd/web:RDAHGDQMGXP : [Sat Nov 21 02:14:46.575450 2015] [core:notice] [pid 1:tid 140159494530944] AH00094: Command line: 'httpd -D FOREGROUND'
2015-11-21 02:21:07 i-a2eb6f7b httpd/web:RDAHGDQMGXP : [Sat Nov 21 02:21:07.933693 2015] [mpm_event:notice] [pid 1:tid 140159494530944] AH00491: caught SIGTERM, shutting down
2015-11-21 02:21:07 i-a2eb6f7b convox/agent:0.5 : Stopped process ba178922a3fb
2015-11-21 02:21:08 i-a2eb6f7b convox/agent:0.5 : Stopping process ba178922a3fb via SIGTERM
```

Todo:
- [x] Log container start event
- [x] Design easy to understand inclusion of instance id, container id, or release ID
- [x] Drop docker container id (since instance ID + process name is unique)
- [x] Design and include log timestamps
- [x] Root cause double logging events

Later:
- [ ] Improve docs and CLI around rolling deploy expectations

### CODE REVIEW

**Comment by nzoschke** [comment]
Here's a design straw man. This includes timestamp, instance ID, release ID, and container start / stop events.

```
Nov 20 12:50:46 convox/agent i-285567e4: Starting container with release RIDVTRGGJEB
Nov 20 12:50:46 web RIDVTRGGJEB i-de64318d: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
Nov 20 12:50:46 web RIDVTRGGJEB i-de64318d: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
Nov 20 12:50:46 web RIDVTRGGJEB i-de64318d: [Wed Nov 18 22:35:46.325249 2015] [mpm_event:notice] [pid 1:tid 140682388391808] AH00489: Apache/2.4.17 (Unix) configured -- resuming normal operations
Nov 20 12:50:47 web RIDVTRGGJEB i-de64318d: [Wed Nov 18 22:35:46.325378 2015] [core:notice] [pid 1:tid 140682388391808] AH00094: Command line: 'httpd -D FOREGROUND'
Nov 20 12:51:22 web RDAHGDQMGXP i-285567e4: [Wed Nov 18 22:36:21.498434 2015] [mpm_event:notice] [pid 1:tid 140715729373056] AH00491: caught SIGTERM, shutting down
Nov 20 12:51:22 convox/agent i-285567e4: Stopping container with release RDAHGDQMGXP via SIGTERM
```

**Comment by ddollar** [comment]
Here's a suggestion:

```
2015-11-20 12:50:46 i-285567e4 convox/agent:0.6 : Starting process 0123456789
2015-11-20 12:50:46 i-de64318d myapp/web:RIDVTRGGJEB httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
2015-11-20 12:50:46 i-de64318d myapp/web:RIDVTRGGJEB httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
2015-11-20 12:50:46 i-de64318d myapp/web:RIDVTRGGJEB httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
2015-11-20 12:50:46 i-de64318d myapp/web:RIDVTRGGJEB httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
2015-11-20 12:51:22 i-285567e4 convox/agent:0.6 Stopping process 0123456789 via SIGTERM
```

**Comment by ddollar** [comment]
We can split and colorize that output during `convox logs` too

**Comment by nzoschke** [comment]
I am still seeing double logging in my tests. I suspect it is a problem in docker engine. This report matches exactly the problem I am seeing, with the same version (1.7.1).

https://forums.docker.com/t/duplicate-logs-appearing-when-querying-container-logs-in-docker-1-7-1/4057

**Comment by csquared** [comment]
+1

**Pull request merged**
